name: Create Release Assets
on:
  push:
    tags:
      - "*"

permissions:
  contents: write
  checks: write
  actions: read
  issues: read
  packages: write
  pull-requests: read
  repository-projects: read
  statuses: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: "Zip plugin"
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: "zip"
          path: "./"
          filename: "./packages/gravityforms-addon-json-emails.zip"
          exclusions: "/packages/* *.git*"

      - name: Upload release binaries
        uses: alexellis/upload-assets@0.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_paths: '["./packages/*.zip"]'
